ForesightMiningSoftwareCorporation/github

.github/actions/shell-with-output/action.yaml, .github/workflows/rust-build.yml, .github/workflows/rust-test.yml, docker/rust-tests/Dockerfile
closes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/37
=> Better test outputs

.github/workflows/rust_private_registry_publish.yml
=> [fix] Additional args should be set for cargo publish

.github/workflows/tag_reusable_workflows.yml
=> [enh] Workflow for tagging and updating release tag

.github/workflows/rust_private_registry_publish.yml
fixes #2
fixes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/64
=> Discord Notification enhancement

.github/workflows/rust-test.yml
fixes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/63
=> [enh] Add non required test to ensure package can be published

.github/workflows/rust-test.yml
Handle part of https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/65
=> [fix] Auto hide old tests comment

.github/workflows/rust-test.yml, docker/rust-tests/Dockerfile
fixes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/67
=> [enh] Switch to tomlq to get crate name in tests

.github/workflows/rust-test.yml
=> fix: use gh_registry_package token

.github/workflows/rust-build.yml, .github/workflows/rust-test.yml
=> feat: switch from artifact to cache (prisma related)

.github/actions/cargo-crate-exists/action.yml
fixes: https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/127
=> fix: Update UpdateCli and ensure we can publish new package

.github/workflows/rust-test.yml
fixes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/141
=> fix: switch rust-test pr comment condition around

.github/workflows/gitleaks.yaml, .pre-commit-config.yaml, Makefile
closes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/122
=> feat: implement gitleaks

.github/actions/shell-with-output/action.yaml, .github/workflows/build_rust_test_images.yaml, .github/workflows/rust-build.yml, .github/workflows/rust-test.yml, .github/workflows/setup_rust_test_images.yaml, docker/rust-tests/Dockerfile
closes ForesightMiningSoftwareCorporation/infrastructure#101
Miri tests are not run by default, but can be enabled using a flag.
=> feat: add miri tests

.github/workflows/rust_binary_publish.yml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/197
=> fix: add missing condition on step

.github/workflows/build_rust_test_images.yaml, .github/workflows/rust-build.yml, .github/workflows/rust-test.yml, .github/workflows/setup_rust_test_images.yaml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/195
Change logic for dry-run test to be required in the publish context when we want to publsih to docker or private reg
=> feat: switch publish dryrun required status based on publish settings

.github/workflows/rust-test.yml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/215
=> feat: use restore-keys to allow for cross-branch cache

.github/workflows/clear-cache-closed-pr.yml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/217
=> feat: add workflow to clear cache from closed pr

.github/workflows/rust-build.yml, .github/workflows/rust-test.yml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/220
I've also decided to remove the `detail` as I feel that it makes non-required easy to overlook 
You can see a run with it here e.g: https://github.com/ForesightMiningSoftwareCorporation/ci_tests/pull/19
=> feat: add doc check test and remove details

.github/workflows/clean_cache.yml
=> chore: Add workflow to auto clean cache of closed pr

.github/workflows/rust-test.yml
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/227
=> fix: if not success -> failure

.github/actions/cargo-crate-exists/action.yml, .github/actions/cargo-public-crate-exists/action.yml, .github/workflows/docker_publish.yml, .github/workflows/rust-build.yml, .github/workflows/rust-test.yml, .github/workflows/rust-update-dependencies.yml, .github/workflows/rust_binary_publish.yml, .github/workflows/rust_private_registry_publish.yml, .github/workflows/rust_public_registry_publish.yml, .github/workflows/setup_rust_test_images.yaml, docker/blast_physics_builder/Dockerfile
fixes ForesightMiningSoftwareCorporation/infrastructure#235 and a part of ForesightMiningSoftwareCorporation/infrastructure#236
=> chore: update default rust version in CI

.github/workflows/rust-test.yml
and fix the check for deny.toml instead of deny.yml
=> fix: use curl instead of wget to fetch deny.toml

.github/actions/shell-with-output/action.yaml, .github/workflows/rust-build.yml, .github/workflows/rust-test.yml
Switch to using a js action to generate workspaces
=> Feat: Rust Workspace matrix generation js action

.github/workflows/rust-build.yml, .github/workflows/rust-test.yml
This is opt-in, by default all tests run when no changes are detected
=> feat: allow skipping tests when no changes to rust workspaces were detected

.github/workflows/rust-test.yml, docker/rust-tests/Dockerfile
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/320
resolves https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/322
=> feat: allow to choose rust version from test run

.github/workflows/rust-test.yml, .github/workflows/rust_binary_publish.yml
update WP app fallback naming in GH workflow
=> update naming for app fallback

.github/workflows/rust-test.yml
Fixes https://github.com/ForesightMiningSoftwareCorporation/orica_libs/issues/1031
=> Azurite service container for tests

.github/workflows/npm_napi_publish.yml
=> chore: Update npm_napi_publish.yml to unblock napi build

.github/workflows/build_orica_server_builder_image_versioned.yaml, docker/orica_server_builder/Dockerfile_versioned
To workaroud this issue - https://github.com/ForesightMiningSoftwareCorporation/orica_libs/issues/2048
=> chore: Unblock build - GitHub Actions build error using 1.77 toolchain
